version: '3.3'

services:
  ubuntu-netology:
    container_name: ubuntu
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - neto
  centos-netology:
    container_name: centos7
    build:
      context: .
      dockerfile: Dockerfile2
    networks:
      - neto
networks:
  neto:
    driver: bridge
    external: false
